name: 'MarketPlace Application Information'
description: 'outputs application information'
inputs:
  bundle_identifier:
    description: 'iOS Bundle Identifier'
    required: false
  version_number:
    description: 'Application Version Number'
    required: false
outputs:
  app_name:
    description: 'application name'
    value: ${{ steps.appstore_information.outputs.app_name }}
  release_date:
    description: 'release date'
    value: ${{ steps.appstore_information.outputs.release_date }}
  version:
    description: 'application version'
    value: ${{ steps.appstore_information.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: "checking latest version for AppStore"
      shell: bash
      id: appstore_information
      run: |
        bundle_identifier=${{ inputs.bundle_identifier }}
        version_number=${{ inputs.version_number }}

        # Get the latest version from AppStore
        app_information=`ruby ${GITHUB_ACTION_PATH}/scripts/appstore.rb ${bundle_identifier} ${version_number}`

        # Json parse
        app_name=$(echo $app_information | jq -r '.app_name')
        release_date=$(echo $app_information | jq -r '.release_date')
        version=$(echo $app_information | jq -r '.version')

        echo "app_name=${app_name}" >> $GITHUB_OUTPUT
        echo "release_date=${release_date}" >> $GITHUB_OUTPUT
        echo "version=${version}" >> $GITHUB_OUTPUT
