name: 'MarketPlace Application Information'
description: 'outputs application information'
inputs:
  market_type:
    description: 'Market Type'
    required: true
  bundle_identifier:
    description: 'iOS Bundle Identifier'
    required: false
outputs:
  app_name:
    description: 'application name'
    value: ${{ steps.appstore_information.outputs.app_name }}
  release_date:
    description: 'release date'
    value: ${{ steps.appstore_information.outputs.release_date }}
  version:
    description: 'application version'
    value: ${{ steps.appstore_information.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: "checking latest version for AppStore"
      shell: bash
      id: appstore_information
      run: |
        bundle_identifier=${{ inputs.bundle_identifier }}

        # Get the latest version from AppStore
        app_information=`ruby ./scripts/appstore.rb ${bundle_identifier}`

        echo "app_name=${app_information['app_name']}" >> $GITHUB_OUTPUT
        echo "release_date=${app_information['release_date']}" >> $GITHUB_OUTPUT
        echo "version=${app_information['version']}" >> $GITHUB_OUTPUT
